"""Pin installed runtime dependencies; development tools stay out of the image."""
from importlib.metadata import distribution
from packaging.requirements import Requirement
from packaging.utils import canonicalize_name
from pathlib import Path

seen = {}
def visit(name):
    name = canonicalize_name(name)
    if name in seen:
        return
    dist = distribution(name)
    seen[name] = dist.version
    for spec in dist.requires or []:
        req = Requirement(spec)
        if req.marker is None or req.marker.evaluate({'extra': ''}):
            visit(req.name)

for name in ['fastapi', 'uvicorn', 'databricks-sdk', 'tzdata']:
    visit(name)
Path('requirements.txt').write_text('# Resolved with Python 3.12; generated by scripts/lock_python.py\n' +
    ''.join(f'{name}=={version}\n' for name, version in sorted(seen.items())))
